### ISSUE TITLE
Plotting custom calendar

### ISSUE THREAD

**Issue by semvijverberg** [AI4S2S/lilio#12]
Okay, unfortunately I cannot install lilio atm: 
![image](https://user-images.githubusercontent.com/35559713/213165389-edf11577-9220-426f-a46f-1fec425c107e.png)
So I cannot verify whether this bugs also exists in lilio (but it does in s2spy). 

The following plotting issue arises when n_targets > 1 (also when using custom calendar):

```
calendar = s2spy.time.AdventCalendar(anchor="12-31", freq='20d', max_lag=1, n_targets=2)
calendar = calendar.map_years(2020, 2020)
calendar.visualize(show_length=True)
```
![image](https://user-images.githubusercontent.com/35559713/213166418-a21124b7-294e-4d81-877a-7a6097ea6442.png)

While if I plot n_targets = 1:
```
calendar = s2spy.time.AdventCalendar(anchor="12-31", freq='20d', max_lag=1, n_targets=2)
calendar = calendar.map_years(2020, 2020)
calendar.visualize(show_length=True)
```
![image](https://user-images.githubusercontent.com/35559713/213166511-d6296c93-3b28-4b30-8542-112c0bcb2c38.png)

Hence, this plotting issue appears when n_targets > 1.

**Comment by semvijverberg** [comment]
This is specific for the anchor_data="12-31"

```
calendar = s2spy.time.AdventCalendar(anchor="10-31", freq='20d', max_lag=1, n_targets=2)
calendar = calendar.map_years(2020, 2021)
calendar.visualize()
```

![image](https://user-images.githubusercontent.com/35559713/213171321-e9ed6004-3fb5-4e3f-ba3e-8f9f4ea73c49.png)

**Comment by BSchilperoort** [comment]
Thanks for reporting this, Sem. I'll have a look.
