### ISSUE TITLE
The fate of pylint

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/lilio#14]
With PR #11 we are moving away from using prospector for linting and checks, and instead using hatch to run the linters we want to run.

However, prospector has a "strictness" parameter, [which disables a whole list of errors and warnings in the linters/checks we were using](https://github.com/PyCQA/prospector/blob/master/prospector/profiles/profiles/strictness_medium.yaml).

I am also not able to reproduce the linter behavior that prospector displayed. What will we use going forward? A customized pylint setup? By default there are way too many false positives.

For now, #11 just uses flake8, to keep things simple and not make the CI fail. Fixing the CI would require a lot of code changes if we want to keep using pylint.

**Comment by Peter9192** [comment]
All for moving away from prospector, but perhaps we can rename the issue to focus on the fate of pylint? That might require some further discussion

**Comment by BSchilperoort** [comment]
We're using ruff now, which integrates pylint checks.
