### ISSUE TITLE
ReadTheDocs not working?

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/lilio#15]
I was wondering if we already have a readthedocs integration. In the repo settings it looks like we do, but the documentation does not seem to be available on readthedocs. 

I'd be happy to set it up fresh, but given that there's already something, perhaps it's better if you first look at it @BSchilperoort, or if you could at least provide some context.

**Comment by BSchilperoort** [comment]
Hi @Peter9192, it's already set up and is working successfully on #11 (see e.g. https://lilio--11.org.readthedocs.build/en/11/ )

![image](https://user-images.githubusercontent.com/12114825/213663972-a26d2688-7419-4192-803a-3f2e24406fc7.png)

**Comment by BSchilperoort** [comment]
Note that once the PR is merged, a docs build for `main` will be available
