### ISSUE TITLE
Do we need a new logo for Lilio?

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/lilio#17]
With a new package comes a new logo?

It's not my strength, but for inspiration, how could we elaborate on the images below?

![image](https://user-images.githubusercontent.com/17080502/213752048-6f396cf5-5123-469c-b642-c505bc53f903.png)
![image](https://user-images.githubusercontent.com/17080502/213753021-42bce39c-b9cc-4080-8ec6-edaf22b909d0.png)
![image](https://user-images.githubusercontent.com/17080502/213752782-a1d77833-299a-4a22-9454-d0933ee3cc67.png)
![image](https://user-images.githubusercontent.com/17080502/213753262-1400a594-c590-4f41-a669-28c989bd4e70.png)
![image](https://user-images.githubusercontent.com/17080502/213753482-84eaf676-806c-43dd-b87a-6612eacd1a9a.png)
![image](https://user-images.githubusercontent.com/17080502/213753513-b276a605-bd58-49ac-bd61-70ae96b1d4c0.png)

@jannesvaningen perhaps you can illuminate us with your amazing graphic design skills?

**Comment by jannesvaningen** [comment]
@Peter9192 thanks for the ideas! This is my first take on the circular idea:
![Asset 6](https://user-images.githubusercontent.com/82503135/217539554-871650f9-1242-4e6e-9200-5cde059cbd4f.png)
Any ideas? I am playing around with the colors a bit now

**Comment by Peter9192** [comment]
Love the spiraling!! Thanks for picking this up! 

My main point for improvement would be that the text currently doesn't blend in very well with the visuals. Perhaps give it some shadow, move it to the bottom/top or even remove it? E.g. the python logo has a version with and without text: 
![image](https://user-images.githubusercontent.com/17080502/217555143-c0e25d14-b4dc-4a2e-b9fe-85cb375c78e7.png).

**Comment by jannesvaningen** [comment]
Thanks for suggestions Peter! We discussed it here and the other suggestion was to make the corners transparent such that the logo itself is circular. I like your suggestion too, we can make several versions with the text next to it, under it or leaving it out. 
To be continued

**Comment by jannesvaningen** [comment]
With text:
![230208 logo_lilio_wtext](https://user-images.githubusercontent.com/82503135/217579949-3a45496f-122e-4f59-9747-e483710d9a36.png)
No text:
![230208 logo_lilio_solo](https://user-images.githubusercontent.com/82503135/217579960-b5a1657d-8213-4c48-97c9-628c6c8041e8.png)

I think they look great now!

**Comment by Peter9192** [comment]
Cool!! Might I suggest to already start use today's latest version on readthedocs? Would be cool to have it when we start advertising the release tomorrow with the blogpost

**Comment by jannesvaningen** [comment]
I'd be cool with that! Let me check if I can edit that with the help of @geek-yang

**Comment by BSchilperoort** [comment]
@jannesvaningen do you have the vector images (svg) for the logo? That would be nice to store on the repo in case any modifications are required

**Comment by jannesvaningen** [comment]
@BSchilperoort 230213 logo_lilio_solo_wtext.svg
230213 logo_lilio_solo.svg
230213 logo_lilio_wtext.svg

**Comment by jannesvaningen** [comment]
![230213 logo_lilio_solo_wtext](https://user-images.githubusercontent.com/82503135/218513719-0ca7de92-187a-4360-a706-9a40afc49b60.svg)
![230213 logo_lilio_solo](https://user-images.githubusercontent.com/82503135/218513727-36690203-c00f-4991-931e-9b63b7acfe8e.svg)
![230213 logo_lilio_wtext](https://user-images.githubusercontent.com/82503135/218513730-d4a1f4e5-155a-42c6-99aa-c21ebd96fb0a.svg)
@BSchilperoort

**Comment by BSchilperoort** [comment]
Thanks @jannesvaningen, however it does seem like the font renders differently. I guess you used a non-standard font? Perhaps you can convert the text to paths, this would make it more shareable. On inkscape this setting is called "Object to Path".

If people don't have the following font installed:
![image](https://user-images.githubusercontent.com/12114825/218673707-df806016-eabb-4ca2-958f-2e9e522692aa.png)
The svg looks like this:
![image](https://user-images.githubusercontent.com/12114825/218674512-831175a5-1b47-43ac-8717-2e67f16696e3.png)

**Comment by jannesvaningen** [comment]
![230222 logo_lilio_solo_textoutline](https://user-images.githubusercontent.com/82503135/220596986-faaffabc-9dda-426b-b64f-c6b69dabfa17.svg)
![230222 logo_lilio_wtext_textoutline](https://user-images.githubusercontent.com/82503135/220596996-f26d9fc4-9462-4fe0-a8a3-c5e01b910906.svg)

@BSchilperoort I think it works like this right?
