### ISSUE TITLE
Using jupyter notebooks more efficiently with github

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/lilio#20]
Up to now we have been updating and commiting _executed_ jupyter notebooks to the repository. Both the cell outputs as well as all the included metadata cause very large diffs.
These large diffs make it difficult to review notebooks without an external tool, and pollute the git history.

I have been thinking about how best to solve these issues, and I think the following workflow could work:

1. Add a pre-commit hook and/or hatch script that cleans up the .ipynb files (strips metadata + output).
2. Add a check to the linter CI to ensure only cleaned up notebooks can be merged into main.
3. When building the documentation, the notebooks should be executed, and then converted to html/md files.
4. The notebooks need to be referred to inside the documentation (so prospective users can see the output of the cells)

Steps 1,2 and 4 are easily possible right now, I not sure yet about how to integrate step 3 in our current setup.

nbconvert _does_ have an `--execute` cli option, and it seems that the nbsphinx plugin of sphinx supports this (see https://nbsphinx.readthedocs.io/en/0.8.12/configuration.html#nbsphinx_execute).

Alternatively there is mkdocs, which has https://github.com/danielfrg/mkdocs-jupyter

**Comment by Peter9192** [comment]
Also see https://github.com/community/community/discussions/37376

**Comment by BSchilperoort** [comment]
> Could we somehow use https://github.com/jupyter/nbdime?

It seems like that new github feature uses nbdime.

> Isn't the default for nbsphinx also to execute the notebooks? 

_Notebooks with no outputs are automatically executed during the Sphinx build process. If, however, there is at least one output cell present, the notebook is not evaluated and included as is._ ([src](https://nbsphinx.readthedocs.io/en/0.7.1/executing-notebooks.html))

> I also appreciate the possibility of inspecting notebooks (including their output) in GitHub, so I'm wondering if there's yet another way

It is convenient to see both in the PR, however this means that with every change in, e.g. the plotting or reprs, notebooks have to be regenerated and committed again. It is also easy to forget to update notebooks when some functionality changes, and this is currently not visible (or tested). 

As the documentation is built and available on readthedocs, someone reviewing a PR can still easily view the output, while also making it possible to focus on the actual code (or markdown) changes in the Github file viewer.

**Comment by Peter9192** [comment]
> It is convenient to see both in the PR, however this means that with every change in, e.g. the plotting or reprs, notebooks have to be regenerated and committed again.

Would it be feasible to automate this with a pre-commit hook, github action, or hatch script? Provided that we can find a way to render nice diffs, I think this would even be an added value as we would be notified that functionality changed (perhaps unintendedly). In that case, the notebooks would serve as a sort of integration test.

**Comment by BSchilperoort** [comment]
Currently the notebooks are checked for if they are cleaned of output by [this action](https://github.com/ResearchSoftwareActions/EnsureCleanNotebooksAction). This makes the diffs clean and clear when reviewing through github.

Notebooks are executed before rendering, and if the execution fails the docs build fails. This will alert us to when the notebooks are broken, but not when outputs change (e.g. slightly different plot output). I think this will make it easier and less work to keep the notebooks up to date.

Being notified of changes in notebook outputs could be nice, but I am not sure if there is an easy and clean way of implementing this, as well as if it's needed. Nearly all code is covered by tests, which serve as a more robust way of asserting that the output does not change.

**Comment by Peter9192** [comment]
Just wanted to point out a related project I recently encountered: [nbdev](https://nbdev.fast.ai/tutorials/git_friendly_jupyter.html#what-are-nbdev-hooks) (and by extension, also checkout [quarto](https://quarto.org/docs/computations/python.html)). Might be relevant if we even reconsider this.

**Comment by BSchilperoort** [comment]
Thanks for letting us know. For other projects (where notebooks are bigger and need certain local data or have a long runtime) nbdev could be interesting.
