### ISSUE TITLE
Add example notebooks to documentation

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/lilio#23]
We have some really nice example notebooks. It would be nice if these are part of the documentation. We could e.g. use [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.12/) and/or [myst-nb](https://github.com/AI4S2S/lilio/blob/main/notebooks/all_about_the_calendar.ipynb)

**Comment by BSchilperoort** [comment]
I agree. We should do this when updating the Lilio notebooks (they are still the old s2spy ones).
