### ISSUE TITLE
Figure not showing properly on the documentation page

### ISSUE THREAD

**Issue by geek-yang** [AI4S2S/lilio#25]
The conceptual illustration figure doesn't display properly on the first page of "Read the Docs" (https://lilio.readthedocs.io/en/latest/).

This can be fixed by using the raw figure link in `README.md`, which in this case should be https://raw.githubusercontent.com/AI4S2S/lilio/main/docs/assets/images/calendar_concept.png

**Comment by BSchilperoort** [comment]
Thanks for noticing this, I fixed it in #26
