### ISSUE TITLE
Anchor_year not sorted

### ISSUE THREAD

**Issue by semvijverberg** [AI4S2S/lilio#29]
I notices that the anchor_year coordinates are not ascending in order.

![image](https://user-images.githubusercontent.com/35559713/216063176-6835b077-198c-41ff-a032-4061872b82ea.png)

This leads to unwanted behavior when slicing across the anchor_year dim:
![image](https://user-images.githubusercontent.com/35559713/216063441-8e0b518e-fce8-457b-8cab-5d83704f7dde.png)

**Comment by BSchilperoort** [comment]
Thanks for reporting this Sem, I've fixed this in #30. The anchor_year and i_interval are now sorted before the resampled data is returned.

**Comment by semvijverberg** [comment]
Thanks @BSchilperoort!
