### ISSUE TITLE
FAIR checklist with sqaaas

### ISSUE THREAD

**Issue by sverhoeven** [AI4S2S/lilio#44]
I ran https://sqaaas.eosc-synergy.eu/#/auth/full-assessment on this repo and it got a silver badge.

```markdown
[![SQAaaS badge](https://github.com/EOSC-synergy/SQAaaS/raw/master/badges/badges_150x116/badge_software_silver.png)](https://api.eu.badgr.io/public/assertions/tVAmKytOTqWwOimvZkdoUg "SQAaaS silver badge achieved")
```

* [SQAaaS Report - AI4S2S_lilio.pdf](https://github.com/AI4S2S/lilio/files/10804278/SQAaaS.Report.-.AI4S2S_lilio.pdf)
* [Verify](https://badgecheck.io/?url=https%3A%2F%2Fapi.eu.badgr.io%2Fpublic%2Fassertions%2FtVAmKytOTqWwOimvZkdoUg?identity__url=https%3A%2F%2Fgithub.com%2FEOSC-synergy%2Flilio.assess.sqaaas%2Fcommit%2F2db5fb2b9b5474dc8097fbeaf689debeda98fefc&amp;identity__url=https%3A%2F%2Fgithub.com%2FEOSC-synergy%2Flilio.assess.sqaaas%2Fcommit%2F2db5fb2b9b5474dc8097fbeaf689debeda98fefc)
* [Go to Badgr's award page](https://api.eu.badgr.io/public/assertions/tVAmKytOTqWwOimvZkdoUg)

In `.howfairis.yml` file put.
```yaml
skip_checklist_checks_reason: Software Quality Assurance as a Service (https://sqaaas.eosc-synergy.eu/) says its OK
```

Lastly rerun `howfairis` to get 5 stars.

**Comment by BSchilperoort** [comment]
I added the `.howfairis.yml` file, however `howfairis` does not seem to pick it up.

To replicate do:
`howfairis https://github.com/AI4S2S/lilio/tree/improvements_3274`

**Comment by BSchilperoort** [comment]
It would be nice if SQAaaS recognized that we don't use a line length of 79. That's the only thing keeping us from having a gold badge.

**Comment by BSchilperoort** [comment]
We have a gold medal now. Adding a .flake8 file worked #48
