### ISSUE TITLE
Lilio feedback at EGU

### ISSUE THREAD

**Issue by BSchilperoort** [AI4S2S/lilio#55]
Last week I presented Lilio at the EGU conference. Sadly, the poster session was on Friday afternoon so the session was not very well attended.

There was some interest, however, many of the people attending seemed mostly focused on emulating NWP-style forecasts. If we would want to capture these use-cases more, we could consider streamlining this more. Although:

- the current way of resampling is probably not the most efficient for this use case
- it would share very little code with the current Lilio

Designing a separate NWP-resampler from scratch is probably simpler.

**Comment by geek-yang** [comment]
Thanks for the update. Given the project hours, I think if there is some low-hanging fruit which makes it possible to serve the weather forecasting community, then it is worthy. But as what you said, our package might not be optimal at this stage for those use cases and to opt for those opportunities means more work for us, then I don't think we should move forward now.

**Comment by geek-yang** [comment]
I think this issue can be closed now.
