### ISSUE TITLE
Inconsistent return type of lilio traintestsplit

### ISSUE THREAD

**Issue by pimmeerdink** [AI4S2S/lilio#61]
Hey guys,

Ten eerste: generally is lilio een top package en lilio gebruiken bespaart veel tijd, dus dat is top :) De interfaces zijn daarnaast over het algemeen intuitief en consistent. Er blijkt echter een uitzondering: de cv.traintestsplit yield de ene keer een lijst, de andere een datarray (afhankelijk of het om meerdere variabelen gaat). Generally zie ik niet zo goed waarom deze inconsistentie optimaal is: zou je niet het liefst altijd een lijst returnen, mogelijk met 1 element? In de praktijk zien we voor onze pipeline, bijvoorbeeld, dat dat het handigste is qua downstream handlen, we moeten nu expliciet deze code erin zetten, om daarna consistent te kunnen zijn, bijvoorbeeld:

```       
 if if not isinstance(x_train, list):
            x_train = [x_train]
            x_test = [x_test]
```

Benieuwd wat jullie denken :)

**Comment by geek-yang** [comment]
Thanks for raising this issue (while, next time could you please put it in English and add a minimum example, that would make my life much easier 😂, thanks).

I think it makes sense to return a list if the input would be a list, and return a single file if the input is a single file. I plan to add a check and will raise a PR for this.
