### ISSUE TITLE
map_years may lead to unexpected behaviour

### ISSUE THREAD

**Issue by semvijverberg** [AI4S2S/lilio#63]
I stumbled upon the following edge case, will led to unexpected behaviour. 

I have a dataset from 1959 to 2012, monthly data. 

The last timestamp is 2012-12-01 (1st of 12 December). 

When I call map_to_data. It assigns self._last_timestamp. 

[Here](https://github.com/AI4S2S/lilio/blob/ee8ff0a9173661d06117f7f2a602df7d8d996860/lilio/calendar.py#L491-L492), it checks is the most right i_interval is larger than the last timestamp (should be the case, as the interval are defined "until" and not "until and including"). However, it does not take into account the input frequency (daily vs monthly, or perhaps weekly). 

I don't have the solution, because it is quite nice that the calendars are, in principle, frequency agnostic. And inferring the temporal frequency from data can be tricky. But I would like to raise the issue, perhaps a warning can be given? Or should we set the input frequency as a non-optional argument?

**Comment by geek-yang** [comment]
Hi @semvijverberg , thanks for spotting this and raising an issue. As what you said, Inferring the temporal frequency can be very tricky, especially given that `lilio` is designed for flexibility and we expect input data with any kinds of frequency distribution. We've thought about this during the design phase and think the current implementation is the best, which enables ample flexibility (without conflicts).

I think maybe it makes sense to signal a warning when `self._map_year(max_year).iloc[0].right == self._last_timestamp`, then at least users with monthly data know what's going on and they could simply modify the last timestamp of their data to avoid the drop of a year. I can address it and raise a PR. Thanks for finding it!

**Comment by BSchilperoort** [comment]
This edge case is now also solved by #75, assuming that your time stamp is in the center of the left and right bounds of the interval it represents...

A follow up issue can be to use `time_bnds` coordinates (if present) so users can either provide a CF-formatted netCDF file with bounds already included, or specify themselves if they need to.
