### ISSUE TITLE
Add multiple types of calendars in addition to AdventCalendar

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/lilio#9]
Currently, we have the `AdventCalendar` as the main class in our time module. This calendar counts down to an anchor date, and divides the year into evenly sized blocks counted in days, not accounting for irregular time conventions such as seasons or months. While this is a perfectly valid approach, there might also be a use case for different calendars. Just some ideas that come to mind:

- DefaultCalendar/ForwardCalendar/DailyCalendar... : the opposite of Advent, counting forward starting from an anchor date. I think having this as a default also clarifies what's special about the AdventCalendar. 
- MonthlyCalendar: similar to DefaultCalendar/AdventCalendar, but instead of counting in days, it will count in months.
- GapCalendar: manually designate a precursor period and a target period, leaving out everything in between and outside these periods.

Perhaps we could consider renaming the `AdventCalendar` to `BackwardCalendar` to contrast it more clearly with the `ForwardCalendar`, or to `BackwardDailyCalendar` to contrast it with a `DailyCalendar`. Alternatively, we could add an argument `backwards=True` or `countdown=True` to make it possible to use the same calendar for both use cases.

To implement multiple calendar, we can make a BaseCalendar class and let the other calendars inherit from it, like so:

```Py
class BaseCalendar():
    # pass

class DailyCalendar(BaseCalendar):
    # pass

class MontlyCalendar(BaseCalendar):
    # pass

# etc.
```
The advantage is that we will be able to reuse functions that can be shared across all Calendars, and that we keep the API more or less uniform across all calendars.

**Comment by BSchilperoort** [comment]
@Peter9192 do you think we should close this issue? Most things discussed here are now implemented or superseded. 

Only the "Forward vs. Backward" calendar is not. However, in some way, this would only change what you call a "precursor" or "target" in the current calendar system. For example, a "BackwardCalendar" would be;
```py
cal = Calendar(anchor="12-31")
cal.add_intervals("target", length="5d")
cal.add_intervals("precursor", length="5d", n=12)
```
While the "ForwardCalendar" would be:
```py
cal = Calendar(anchor="12-31")
cal.add_intervals("precursor", length="5d")
cal.add_intervals("target", length="5d", n=12)
```

**Comment by Peter9192** [comment]
Yes, I agree.
